"""empty message

Revision ID: 11298a876525
Revises: 97ed9960a50b
Create Date: 2022-04-04 22:05:49.616994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11298a876525'
down_revision = '97ed9960a50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping-cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping-cart')
    # ### end Alembic commands ###
