"""empty message

Revision ID: 283179acc04a
Revises: 
Create Date: 2022-03-07 19:15:43.232916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283179acc04a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('Description', sa.String(length=2048), nullable=True),
    sa.Column('type', sa.Enum('Accessories', 'Tops', 'Bikini_and_Coverup', name='producttypes'), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('color', sa.Enum('red', 'green', 'blue', 'purple', 'orange', 'yellow', 'multi_colored', 'white', name='productcolor'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('products')
    # ### end Alembic commands ###
